INSERT INTO dbo.WishlistItem (id, name, price_in_aud, description, url, image_url) VALUES
(1,
 'Bike helmet',
 32.00,
 'Adult bike helmet similar to Rosebank Shakedown Helmet - Matte Black (commuter style, Australian Standards certified).',
 'https://www.bigw.com.au/sports-leisure/bikes-accessories/helmets/adult-helmets/c/6711103100',
 'https://www.bigw.com.au/medias/sys_master/images/images/h92/h02/45487730065438.jpg'),

(2,
 'Bike',
 600.00,
 'Flat-bar fitness / commuter bike such as the 2024 Marin Fairfax 1 or Specialized Sirrus 1.0.',
 'https://bikesonline.com.au/products/2024-marin-fairfax-1-urban-bike',
 'https://bikesonline.com.au/cdn/shop/files/2022_FAIRFAX_1-564777.jpg'),

(3,
 'Nice beers',
 80.00,
 'If you somehow find some nice imported beers (such as Estrella Damm Inedit, 1906 Black Coupage, Stiegl Goldbrau, Weihenstephaner Kristall), I would slurp them up.',
 'https://www.danmurphys.com.au/product/dm_344110/stiegl-goldbrau-lager-330ml-bottle',
 'https://media.danmurphys.com.au/dmo/product/344110-1.png'),

(4,
 'Apfel Zimt Gluhwein',
 18.00,
 'Sternthaler Apfel Zimt Gluhwein (Nurnberger style mulled apple wine), 1L bottle.',
 'https://www.germanliquor.com.au/products/nurnberger-apfel-zimt-gluhwein-1l',
 'https://www.germanliquor.com.au/cdn/shop/files/Gluhapfel.png'),

(5,
 'Rice cooker',
 250.00,
 'Rice cooker with preferably a stainless steel inner pot.',
 'https://www.unclebuffalo.com.au/products/buffalo-stainless-steel-inner-pot-boilsteam-rice-cooker-5-cups?variant=62067714490527&country=AU&currency=AUD',
 'https://www.unclebuffalo.com.au/cdn/shop/files/12_3f8cea27-0550-44d5-b8c7-c98838c4b94c.png'),

(6,
 'Steam gift card',
 20.00,
 'Steam digital gift cards range from $20-$100. Add to my pile of shame. :)',
 'https://www.jbhifi.com.au/collections/digital-content-and-gift-cards/steam-gift-cards',
 'https://www.jbhifi.com.au/cdn/shop/files/760832-Product-0-I-638840265606199738.jpg'),

(7,
 'Flipper Zero',
 395.00,
 'Flipper Zero is a multi-tool for pentesting, radio and access control experiments.',
 'https://ozhack.com/collections/flipper-zero',
 'https://ozhack.com/cdn/shop/files/Flipper-Zero_1024x1024_2x_e8a2e7ef-1d45-4e49-88fa-eafa303216c6.webp'),

(8,
 'Gorgeous Geisha tea',
 18.00,
 'Gorgeous Geisha green tea blend, loose leaf.',
 'https://www.t2tea.com/en/au/gorgeous-geisha-loose-leaf-icon-tin-100g-T115AI135.html',
 'https://cdn.intelligencebank.com/au/share/NOrD/1VN0z/8W8eq/preset=pB6BA/T115AI135_gorgeous_geisha_100g_icon_tin_2023_expanded'),

(9,
 'New York Breakfast',
 34.00,
 'New York Breakfast black tea, loose leaf.',
 'https://www.t2tea.com/en/au/new-york-breakfast-loose-leaf-icon-tin-100g-T125AI139.html',
 'https://cdn.intelligencebank.com/au/share/NOrD/1VN0z/0rKOz/preset=pB6BA/T125AI139_new_york_breakfast_100g_icon_tin_2023_expanded'),

(10,
 'Shincha Green Tea',
 34.00,
 'Shincha first harvest green tea from ITO EN Australia, about 100g pack.',
 'https://itoen.com.au/products/shincha',
 'https://itoen.com.au/cdn/shop/products/MGP18001_ItoEnWebProducts-056-copy_2048x2048.jpg'),

(11,
 'Whisky',
 125.00,
 'I love a nice whisky, for example Suntory Chita, Amber Lane Equinox or Starward Honeycomb.',
 'https://whisky.estate/product/amber-lane-equinox-australian-single-malt-whisky/',
 'https://whisky.estate/wp-content/uploads/2025/06/Amber-Lane-Equinox.png'),

(12,
 'Herman Miller chair',
 1050.00,
 'Second hand Herman Miller Aeron ergonomic office chair with posture fit. Armrest optional.',
 'https://kellysofficefurniture.com.au/product/used-vintage-furniture/all-used-vintage/original-herman-and-miller-second-hand-chair/',
 'https://kellysof.b-cdn.net/wp-content/uploads/IMG_2171-600x600.png.webp'),

(13,
 'Pulsar Xlite V4',
 160.00,
 'Pulsar Xlite V4 Medium wireless gaming mouse (white preferred but black is okay too).',
 'https://www.ple.com.au/products/673307/pulsar-xlite-v4-54g-lightweight-wireless-gaming-mouse-white',
 'https://plecom.imgix.net/iit-419380-673307.png'),

(14,
 'Garmin Drive 53 GPS',
 289.00,
 'Garmin Drive 53 AU car GPS navigator (for L and P plate driving navigation).',
 'https://www.jbhifi.com.au/products/garmin-drive-53-au-nz-gps-navigation',
 'https://www.jbhifi.com.au/cdn/shop/products/636792-Product-8-I-638180997603990917.jpg'),

(15,
 'UNO No Mercy',
 12.00,
 'UNO Show Em No Mercy Edition card game, the extra brutal house-rule style UNO variant.',
 'https://www.target.com.au/p/mattel-uno-show-em-no-mercy/69308901',
 'https://assets.target.com.au/transform/1825cc43-c4c8-4206-a169-281f4f43d769/69308901-IMG-000?io=transform%3Afit%2Cwidth%3A1400%2Cheight%3A1600&output=webp&quality=90'),

(16,
 'Cascadia board game',
 60.00,
 'Cascadia tile-laying and token-drafting board game about Pacific Northwest habitats and wildlife.',
 'https://www.bigw.com.au/product/cascadia-board-game/p/9900115082',
 'https://www.bigw.com.au/medias/sys_master/images/images/h2d/h6b/104064773947422.jpg'),

(17,
 'Wavelength',
 50.00,
 'Wavelength social guessing party game for teams.',
 'https://www.bigw.com.au/product/wavelength/p/6008045',
 'https://www.bigw.com.au/medias/sys_master/images/images/h91/hc5/65471094587422.jpg'),

(18,
 'Shake Hands book',
 30.00,
 'Shake Hands with the Devil: The Failure of Humanity in Rwanda by Romeo Dallaire.',
 'https://www.goodreads.com/book/show/215758.Shake_Hands_with_the_Devil',
 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1438841634i/215758.jpg'),

(19,
 'Clay target voucher',
 189.00,
 'Clay target shooting with live ammo experience voucher from RedBalloon, preferably for 2 to do with you! :)',
 'https://www.redballoon.com.au/product/clay-target-shooting-with-live-ammo/HTT001-M.html',
 'https://redballoon.com.au/dw/image/v2/BCRD_PRD/on/demandware.static/-/Sites-rb-au-catalog/default/images/products/HTT001-M/zbqn4as8v1wzsmglghlr.jpg');